name: Build and Release!

on:
  push:
      tags:
        - "*"

jobs:
  build-for-linux:
    name: Build for Linux!
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      
      - name: Start building!
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          zip -j x86_64-ci-cd-demo-linux-gnu.zip target/x86_64-unknown-linux-gnu/release/ci-cd-demo
      
      - name: Define Release Information!
        id: define_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: |
            [RELEASE] ci-cd-demo v${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload assets to release!
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.define_release.outputs.upload_url }}
          asset_path: x86_64-ci-cd-demo-linux-gnu.zip
          asset_name: x86_64-ci-cd-demo-linux-gnu.zip
          asset_content_type: application/zip